import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import DashboardWrapper from "./dashboardWrapper";
import AuroraBackground from "@/(components)/background/AuroraBackground"; // 💫 배경 import
import BackgroundSlideshow from "@/(components)/background/BackgroundSlideshow";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pel-World",
  description: "Generated by create next app",
  icons: {
    icon: "/images/pelicanic_icon.ico",
    
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 💫 전역 Aurora 배경 */}
        {/* <AuroraBackground /> */}
        {/* <BackgroundSlideshow /> */}
        
        {/* 💬 콘텐츠 z-10으로 표시 */}
        <div className="relative z-10">
          <DashboardWrapper>{children}</DashboardWrapper>
        </div>
      </body>
    </html>
  );
}
